---
- name: Add Java repository to sources
  apt_repository: repo='ppa:webupd8team/java'
  sudo: true

- name: Autoaccept license for Java
  shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections
  sudo: true

- name: Update APT package cache
  apt: update_cache=yes
  sudo: true

- name: Install Java 8
  apt: pkg=oracle-java8-installer state=latest
  sudo: true

- name: Set Java 8 Env
  action: apt pkg=oracle-java8-set-default state=latest
  sudo: true

- name: Install git, maven, nodejs, npm
  apt: 
    pkg: "{{item}}"
    state: present
    update_cache: yes
  with_items:
    - git
    - maven
    - nodejs-legacy
    - npm
  become: true
  become_user: root